dist: trusty
language: cpp
env:
 - BUILD_KCOREADDONS=true
 - BUILD_KCOREADDONS=false
before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt542-trusty
 - if [ "$BUILD_KCOREADDONS" = true ]; then sudo add-apt-repository ppa:kubuntu-ppa/backports; fi
 - sudo apt-get update -qq
 - sudo apt-get install -y qt54base qt54declarative qt54quickcontrols
 - if [ "$BUILD_KCOREADDONS" = true ]; then sudo apt-get install kcoreaddons; fi
install:
 - source /opt/qt54/bin/qt54-env.sh
 - mkdir build && cd build
 - cmake ../
 - make
script: true

