language: cpp
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libqt5core5a libqt5gui5 libqt5network5 libqt5qml5 libqt5quick5 libqt5quickwidgets5 libqt5widgets5
install:
 - mkdir build && cd build
 - cmake ../
 - make

